spring.application.name=spring-api-jwt


spring.datasource.url=jdbc:mysql://localhost:3306/security_jwt_db12?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#jwt.secret doit etre long
# Configuration JWT
jwt.secret=MySuperSecretKeyForJwtAuthentication123456
jwt.expiration=3600000   #periode de temps d'expiration